var quotes = [
//1
	'7. Cu cât este mai mare intelectul cuiva, cu atât mai multă originalitate descoperă în ceilalți. Oamenii obișuiți nu găsesc nici o diferență între ceilalți oameni.',
	'8. Există mulți oameni care ascultă predica la fel cum ascultă vecernia.',
	'17. Râurile sunt drumuri care curg și ne duc oriunde vrem să ajungem.',
	'19. Ultimul lucru pe care îl stabilește cineva care scrie o carte este cel care trebui pus cel dintâi.',
	'23. Cuvintele dispuse diferit au semnificații diferite și semnificațiile diferite înșiruite diferit au efecte diferite.',
	'26. Elocvența este o pictură a gândului; și aceia care, după ce au pictat-o, mai adaugă ceva, fac un tablou în locul unui portret.',
	'38. Poetul nu este un om onest.',
	'39. Dacă fulgerul ar lovi locurile joase etc., poeții și cei care nu pot decât să raționeze în privința lucrurilor de acest gen, ar duce lipsă de dovezi.',
	'42. Să numești pe un rege "prinț" este plăcut, căci îi micșorezi rangul.',
	'44. Vrei ca lumea să gândească bine despre tine? Nu vorbi.',
	'46. Autorul vorbelor de spirit are un caracter rău.',
	'51. Sceptic în loc de îndărătnic.',
//2
	'69. Infintul, media. Când citim prea repede sau prea încet, nu înțelegem nimic',
	'84. Imaginația amplifică obiectele mici astfel încât să ne umple sufletele cu o percepere fantastică și cu o insolență impetuasă; micșorează măreția după mărimea ei, ca atunci când vorbește cu Dumnezeu.',
	'102. Unele vicii pun stăpânire pe noi numai prin intermediul altora și acestea, asemenea ramurilor, cad odată cu retezarea trunchiului.',
	'108. Deși este posibil ca Oamenii să fie prea puțin interesați de ceea ce spun, nu trebuie să concluzionăm neaparat din asta că nu mint; căci există oameni care mint de dragul mințitului.',
	'110. Conștiința falsității plăcerilor actuale și ignorarea vanității plăcerilor absente, provocă inconstanță',
	'116. Gândurile. Totul este unul, totul este diferit. Câte naturi există în om? Câte vocații? Și prin ce întâmplare fiecare om obișnuit alege ceea ce a auzit că este prețuit? Bine găsită această întorsătură. Bine făcut, tocul.',
	'118. Talentul preponderent, care le domină pe celelalte.',
	'120. Natura diverifică și imită; arta imită și diversifică.',
	'124. Vedem lucrurile nu doar din alte direcții, dar și cu alți ochi; nu ne dorim nicidecum să le vedem la fel.',
	'125. Contrariile. omul este un mod natural credul și incredul, timid și repezit.',
	'126. Descrierea omului: dependență, dorință de independență, nevoie.',
	'127. Condiția omului: inconstanță, oboseală, neliniște.',
	'129. Natura noastră constă în mișcare; repausul complet înseamnă moarte.',
	'130. Neliniștea. Dacă un soldat sau un muncitor cu brațele, se plânge de greutatea meșteșugului lui, pune-l să nu facă nimic.',
	'134. Cât de inutilă este pictura, care atrage admirația prin asemănarea lucrurilor, ale căror originale nu le adimrăm!',
	'136. Un fleac ne consolează, pentru că un fleac ne tulbură.',
	'137. Fără a examina fiecare țel în parte, este suficient să-l înțelegem cu divertisment.',
	'138. Omul își face în mod natural meseria oriunde numai în camera lui nu.',
	'145. Un singur gând ne preocupă; nu ne putem gândi la două lucruri în același timp. Din fericire pentru noi, potrivit lumii, nu potrivit lui Dumnezeu.',
	'154. Nu am nici un prieten în folosul tău.',
	'157. Contradicție: disprețul față de existență, să mor degeaba, ura față de existență.',
	'163. Vanitatea. Cauzele și efectele iubirii: Cleopatra',
	'166. Distracția. Moartea este mai ușor de suportat fără să te gândești la ea, decât gândul la moarte în lipsa unui pericol.',
//3
	'188. În fiecare dialog și discurs, trebuie să fim în stare să le spunem celor care se simt ofensați, "De ce anume vă plângeți?"',
	'196. Oamenilor le lipsește inima; nu vor să se împrietenească cu ea.',
	'198. Sensibilitatea omului față de nimicuri și insensibilitatea lui față de lucrurile mari, indică o ciudată inversiune.',
	'204. Dacă ar trebui să dedicăm opt ore din viață, ar trebui să dedicăm o sută de ani.',
	'206. Liniștea eternă a acestor spații infinte mă înfricoșează.',
	'207. Câte împărății nu ne cunosc!',
	'209. Ești mai puțin sclav decât ești iubit și preferat de stăpânul tău? Situația ta este pe bună dreptate mai bună, sclavule. stăpânul tău te preferă; curând te va bătea.',
	'212. Instabilitatea. E un lucru îngrozitor să simțim că tot ceea ce avem ne alunecă printre degete.',
	'213. Între noi și Rai sau Iad este doar viață care e cel mai fragil lucru din lume.',
	'215. Să te temi de moarte în lipsa unui pericol și nu în prezența pericolului, căci trebuie să fii om.',
	'216. Doar moartea subită; este temută de aceea confesorii stau alături de seniori.',
	'221. Ateii ar trebui să spună ce e absolut evident: nu este absolut evident că sufletul este material',
	'224. Cât pot să urăsc neghiobia de a nu se crede în Euharistie etc.! Dacă Evangheliile sunt adevărate, dacă Iisus Hristos este Dumnezeu, care mai este dificultatea?',
	'225. Ateismul dovedește puterea a minții, dar numai într-o anumită măsură.',
	'228. Obiecția ateilor: "Dar nu avem lumină".',
	'232. Mișcarea infinită, punctul care umple totul, momentul de repaos; infintul fără cantitate indivizibil și infinit.',
	'241. Ordinea. Mi-ar fi mult mai frică să nu greșesc și să constat că religia creștină are dreptate, decât sâ nu greșesc crezând că are dreptate.',
//4
	'249. Să-ți pui speranțele în formalisme înseamnă supersitiție, dar înseamnă mândrie să nu fii dispus să te supui lor.',
	'253. Două extreme: excluderea rațiunii, admiterea numai a rațiunii.',
	'269. supunearea înseamnă folosirea rațiunii, în aceasta constă adevăratul creștinism.',
	'272. Nu există nimic care să se conformeze atât de bine la rațiune ca această tăgăduire a rațiunii.',
	'280. Cunoașterea lui Dumnezeu este foarte departe de iubirea pentru Dumnezeu.',
//5
	'295. Al meu, al tău. "câinele ăsta e al meu", a spus copilul sărac, "acesta este locul meu sub soare". Iată începutul imaginii uzurpării pe tot pământul.',
	'300. Când un om puternic înarmat își păzește averea, averea lui e în pace',
	'305. Elvețienii sunt ofensați dacă li se spune gentilomi și se dovedesc a fi adevărații plebei pentru a fi considerați demni de o funcție înaltă.',
	'309. Justiția. Așa cum obiceiul determină ce este agreabil, la fel se întâmplă și cu justiția.',
	'312. Justiție înseamnă ceea ce este instaurat; și astfel toate legile noastre instaurate vor fi considerate obligatoriu ca fiind juste, fără a fi cercetate, de vreme ce sunt instaurate.',
	'321. Copii sunt uluiți când își văd tovarășii respectații.',
	'336. Motivele efectelor. Trebuie să ne păstrăm secretă gândirea și să judecăm totul cu ea, vorbind însă asemena oamenilor.',
//6
	'344. Instinct și rațiune, mărcile a două naturi.',
	'345. Rațiunea ne poruncește mult mai imperios decât un stăpân; căci nesocotind-o pe prima suntem nenorociți și nesupunându-ne celui de-al doilea, suntem nebuni.',
	'346. Gândirea este grandoarea omului.',
	'349. Imaterialitatea sufletului. Filosofii care și-au dominat pasiunile. Ce altă materie ar mai putea face asta?',
	'352. Forța virtuții unui om nu trebuie măsurată după eforturile sale ci după viața lui obișnuită.',
	'356. Hrănirea corpului se face puțin câte puțin. Plinătatea hrănirii și puținătatea subsanței.',
	'358. Omul nu este nici înger și nici brută și păcat este că cel care o face pe îngerul, o face și pe bruta.',
	'369. Memoria este necesară pentru toate operațiile rațiunii.',
	'379. Nu este bine să ai prea multă libertate. Nu este bine să ai tot ceea ce îți dorești.',
	'396. Două lucruri îl învață pe om despre natura lui; instinctul și experiența.',
	'414. Omul este într-atât de necesar nebun, încât a nu mai fi nebun echivalează cu altă formă de nebunie.',
	'419. Nu-l voi lăsa pe om să se bazeze pe el însuși sau pe altul, cu scopul de a-l lăsa fără un refugiu și fără odihnă',
	'422. Este bine să fii obosit și plictisit de căutarea în van a adevărului în bine ca să ne putem întinde brațele către Mântuitor.',
//7
	'438. Dacă omul nu este făcut pentru Dumnezeu, de ce este fericit numai întru Dumnezeu? Dacă omul este făcut pentru Dumnezeu, de ce este el atât de opus lui Dumnezeu?',
	'439. Natura stricată. Omul nu acționează prin rațiune care constituie ființa lui',
	'454. Injustiția. Nu s-au descoperit alte mijloace pentru satisfacerea depravării fără a le face rău altora.',
	'456. Este o judecată pervertită care îl face pe im să se pună deasupra lumii și să prefere propriul bine și perpetuarea norocului și a vieții proprii, în detrimentul restului lumii!',
	'461. Cele trei depravări au creat trei secte; și filosofii nu au făcut altceva decât să ia calea uneia din cele trei depravări.',
	'496. Experiența ne face să vedem diferența enormă dintre pietate și bunătate',
	'503. Filosofii au consacrat viciile, punându-le lui Dumnezeu însuși. Creștinii au consacrat virtuțiile',
	'522. Legea impune ceea ce nu dă. Grația divină dă ceea ce impune.',
	'523. Toată credința constă în Iisus Hristos și în Adam și toată moralitatea în depravare și grație divină',
	'528. Iisus Hristos este Dumnezeu de care ne apropiem fără mândrie și în fața căruia ne simțim umili fără disperare.',
	'534. Există doar două feluri de oameni dreptcredincioși: credincioșii care se cred pe ei înșiși păcătoși; restul, păcătoși care se cred pe ei înșiși dreptcredincioși.',
	'541. Nimeni nu este atât de fericit ca un creștin adevărat, nici atât de rațional, virtuos sau prietenos.',
	'549. Nu este imposibil, ci și inutil să-l cunoști pe Dumnezeu fără Iisus Hristos.',
//8
	'558. Ce vom putea concluziona din întunericul nostru, dacă nu nevrednicia noastră?',
	'580. Natura are perfecțiuni pe care să le arate ca dovadă că este imaginea lui Dumnezeu; și unele defecte care să arate că nu este decât o imagine.',
//9
	'590. Omul trebuie să fie sincer în toate religiile; devărații păgâni, adevărații evrei, adevărații creșstini.',
	'600. Oricare om poate să facă ce a făcut Mahomed; căci el nu a făcut niciun miracol, iar venirea lui nu a fost proorocită. Nimeni nu poate să facă ce a făcut Iisus Hristos.',
//10	
	'664. Model. Dumnezeu s-a folosit de depravarea evreilor ca să-i dea lui Iisus Hristos mijloacele care le-a adus remediul pentru depravarea lor.',
	'671. Evreii care au fost chemați să supună popoare și regi, au fost sclavii păcatului; și creștinii, a căror chemare a fost să fie slujitori și supuși, sunt copii liberi.',
//11
	'698. Sinagoga a precedat biserica; evreii, pe creștini. Profeții au anunțat creștinii; Sfântul Ioan pe Iisus Hristos',
	'699. Este o slavă să vezi cu ochii credinței istoria lui Irod și a lui Cezar',
	'707. Profeții. Momentul, profețit de starea poporului evreu, de starea străinilor, de starea templului, de numărul anilor.',
	'717. Profeții. Promisiunea cu David va avea întotdeauna urmași.(Ieremia, 13-13)',
	'725. Profeții. Convertirea egiptenilor(Isaia, 19-19); un altar în Ecgipt pentru Dumnezeu cel adevărat.',
//12
	'739. Profeții au poruncit neproorociți. Sfinții au fost proorociți, însă nu au făcut profeții. Iisus a și profețit, a și fost profețit.',
	'748. În vremea Mesiei, oamenii s-au împărțit. Cei spirituali, L-au îmbrățisat pe Mesia și cei cu mințile mai brute au rămas să slujească drept martori ai Lui.',
	'764. Biserica a avut dificultăți la fel de mari să arate că Iisus Hristos a fost om, împotriva celor care negau acest lucru, ca și pentru a dovedi că El era Dumnezeu; și probabilitățile erau la fel de mari.',
	'774. Iisus Hristos pentru totți, Moise pentru o seminție.',
	'784. Iisus Hristos nu a vrut mărturia diavolilor, nici a celor care nu fuseseră chemați, ci pe a lui Dumnezeu și a lui Ioan Botezătorul.',
	'796. Iisus Hristos nu spune că El nu este din Nazaret, ca să-i lase pe cei răi în orbirea lor; nici că este fiul lui Iosif',
//13
	'805. Cele două reguli fundamentale; una interioară, cealaltă exterioară; grația divină și minunile; ambele supranaturale.',
	'806. Minunile și adevărul sunt necesare, deoarece este necesar să convingi omul pe de-a întregul, trup și minte.',
	'807. În toate timpurile, fie omul a vorbit cu Dumnezeu, fie Dumnezeu a vorbit cu omul.',
	'811. Dacă nu ar fi existat minunile, nu ar fi existat păcatul să nu se creadă în Iisus Hristos',
	'812. Ar trebui "Să nu fiu creștin, dacă n-ar fi fost minunile", a spus Sfântul Augustin.',
	'815. Nu este posibil să ai o credință rațională împotriva minunilor.',
	'816. Necredincioșii cei mai creduli. Cred în minunile lui Vespasian, ca să nu creadă în cele ale lui Moise.',
	'830. Profețiile erau ambigue; nu mai sunt astfel.',
	'831. Cele cinci afirmații erau ambigue; nu mai sunt astfel.',
	'837. Că trebuie să-l iubim numai pe Dumnezeu este un lcuru atât de evident încât nu este nevoie de minuni ca să fie dovedit.',
	'855. Oamenii cred în minuni. Corupi religia ori în favoare prietenilor, ori împotriva dușmanilor. O așezi după voia ta.',
//14
	'858. Istoria bisericii ar trebui să se numească pe drept cuvânt istoria adevărului.',
	'859. E bine să fii corabie în furtună, când ești sigur că nu te scufunzi. Persecuțiile care tulbură biserica de acest fel sunt.',
	'861. Biserica se află într-o stare excelentă când este sprijinită numai de Dumnezeu.',
	'863. Cu toții greșesc cu atât mai periculos, cu cât urmează fiecare un singur adevăr. Greșeala lor nu stă în urmarea unui fals, ci în neurmarea unui alt adevăr.',
	'883. Răii care m-au obligat să vorbesc despre bazele religiei.',
	'895. Oamenii nu fac niciodată răul atât de complet și de bucuroși ca atunci când îl fac din convingerea religioasă.',
	'896. Este în zadar că biserica a stabilit cuvintele anatemă, erezie etc. sunt folostie împotriva ei.',
	'900. Cel care spune care e semnificația Scriptuirlor și nu o ia din Scripturi, este un dușman al Scriptuirlor.(Sfântul Augustin, Despre doctrica creștină).',
	'913. Probabilitatea. Oricine o poate folosi; nimeni nu o poate lua.',
	'914. Îi permit desfrâului să acționeze și controlează scrupulele; când de fapt ar trebui să fie invers.',
	'918. Îndepărtează probabilitatea și nu mai poți face pe plac lumii; dă-i siguranță și nu mai poți să nu-i fii pe plac.',
	'923. Nu numai iertarea păcatelor alungă păcatele prin taina pentenței, ci căinț, care nu este adevărată dacă nu caută taina.'

]

function newQuote()
{
	var randomNumber = Math.floor(Math.random() * (quotes.length));
	document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];
}