var quotes = [
	'7. Cu cât este mai mare intelectul cuiva, cu atât mai multă originalitate descoperă în ceilalți. Oamenii obișuiți nu găsesc nici o diferență între ceilalți oameni.',
	'8. Există mulți oameni care ascultă predica la fel cum ascultă vecernia.',
	'17. Râurile sunt drumuri care curg și ne duc oriunde vrem să ajungem.',
	'19. Ultimul lucru pe care îl stabilește cineva care scrie o carte este cel care trebui pus cel dintâi.',
	'23. Cuvintele dispuse diferit au semnificații diferite și semnificațiile diferite înșiruite diferit au efecte diferite.',
	'26. Elocvența este o pictură a gândului; și aceia care, după ce au pictat-o, mai adaugă ceva, fac un tablou în locul unui portret.',
	'38. Poetul nu este un om onest.',
	'39. Dacă fulgerul ar lovi locurile joase etc., poeții și cei care nu pot decât să raționeze în privința lucrurilor de acest gen, ar duce lipsă de dovezi.',
	'42. Să numești pe un rege "prinț" este plăcut, căci îi micșorezi rangul.',
	'44. Vrei ca lumea să gândească bine despre tine? Nu vorbi.',
	'46. Autorul vorbelor de spirit are un caracter rău.',
	'51. Sceptic în loc de îndărătnic.',

	'69. Infintul, media. Când citim prea repede sau prea încet, nu înțelegem nimic',
	'84. Imaginația amplifică obiectele mici astfel încât să ne umple sufletele cu o percepere fantastică și cu o insolență impetuasă; micșorează măreția după mărimea ei, ca atunci când vorbește cu Dumnezeu.',
	'102. Unele vicii pun stăpânire pe noi numai prin intermediul altora și acestea, asemenea ramurilor, cad odată cu retezarea trunchiului.',
	'108. Deși este posibil ca Oamenii să fie prea puțin interesați de ceea ce spun, nu trebuie să concluzionăm neaparat din asta că nu mint; căci există oameni care mint de dragul mințitului.',
	'110. Conștiința falsității plăcerilor actuale și ignorarea vanității plăcerilor absente, provocă inconstanță',
	'116. Gândurile. Totul este unul, totul este diferit. Câte naturi există în om? Câte vocații? Și prin ce întâmplare fiecare om obișnuit alege ceea ce a auzit că este prețuit? Bine găsită această întorsătură. Bine făcut, tocul.',
	'118. Talentul preponderent, care le domină pe celelalte.',
	'120. Natura diverifică și imită; arta imită și diversifică.',
	'124. Vedem lucrurile nu doar din alte direcții, dar și cu alți ochi; nu ne dorim nicidecum să le vedem la fel.',
	'125. Contrariile. omul este un mod natural credul și incredul, timid și repezit.',
	'126. Descrierea omului: dependență, dorință de independență, nevoie.',
	'127. Condiția omului: inconstanță, oboseală, neliniște.',
	'129. Natura noastră constă în mișcare; repausul complet înseamnă moarte.',
	'130. Neliniștea. Dacă un soldat sau un muncitor cu brațele, se plânge de greutatea meșteșugului lui, pune-l să nu facă nimic.',
	'134. Cât de inutilă este pictura, care atrage admirația prin asemănarea lucrurilor, ale căror originale nu le adimrăm!',
	'136. Un fleac ne consolează, pentru că un fleac ne tulbură.',
	'137. Fără a examina fiecare țel în parte, este suficient să-l înțelegem cu divertisment.',
	'138. Omul își face în mod natural meseria oriunde numai în camera lui nu.',
	'145. Un singur gând ne preocupă; nu ne putem gândi la două lucruri în același timp. Din fericire pentru noi, potrivit lumii, nu potrivit lui Dumnezeu.',
	'154. Nu am nici un prieten în folosul tău.',
	'157. Contradicție: disprețul față de existență, să mor degeaba, ura față de existență.',
	'163. Vanitatea. Cauzele și efectele iubirii: Cleopatra',
	'166. Distracția. Moartea este mai ușor de suportat fără să te gândești la ea, decât gândul la moarte în lipsa unui pericol.',

	'188. În fiecare dialog și discurs, trebuie să fim în stare să le spunem celor care se simt ofensați, "De ce anume vă plângeți?"',
	'196. Oamenilor le lipsește inima; nu vor să se împrietenească cu ea.',
	'198. Sensibilitatea omului față de nimicuri și insensibilitatea lui față de lucrurile mari, indică o ciudată inversiune.',
	'204. Dacă ar trebui să dedicăm opt ore din viață, ar trebui să dedicăm o sută de ani.',
	'206. Liniștea eternă a acestor spații infinte mă înfricoșează.',
	'207. Câte împărății nu ne cunosc!',
	'209. Ești mai puțin sclav decât ești iubit și preferat de stăpânul tău? Situația ta este pe bună dreptate mai bună, sclavule. stăpânul tău te preferă; curând te va bătea.',
	'212. Instabilitatea. E un lucru îngrozitor să simțim că tot ceea ce avem ne alunecă printre degete.',
	'213. Între noi și Rai sau Iad este doar viață care e cel mai fragil lucru din lume.',
	'215. Să te temi de moarte în lipsa unui pericol și nu în prezența pericolului, căci trebuie să fii om.',
	'216. Doar moartea subită; este temută de aceea confesorii stau alături de seniori.',
	'221. Ateii ar trebui să spună ce e absolut evident: nu este absolut evident că sufletul este material',
	'224. Cât pot să urăsc neghiobia de a nu se crede în Euharistie etc.! Dacă Evangheliile sunt adevărate, dacă Iisus Hristos este Dumnezeu, care mai este dificultatea?',
	'225. Ateismul dovedește puterea a minții, dar numai într-o anumită măsură.',
	'228. Obiecția ateilor: "Dar nu avem lumină".'
	'232. Mișcarea infinită, punctul care umple totul, momentul de repaos; infintul fără cantitate indivizibil și infinit.',
	'241. Ordinea. Mi-ar fi mult mai frică să nu greșesc și să constat că religia creștină are dreptate, decât sâ nu greșesc crezând că are dreptate.',

	'249. Să-ți pui speranțele în formalisme înseamnă supersitiție, dar înseamnă mândrie să nu fii dispus să te supui lor.',
	'253. Două extreme: excluderea rațiunii, admiterea numai a rațiunii.',
	'269. supunearea înseamnă folosirea rațiunii, în aceasta constă adevăratul creștinism.',
	'272. Nu există nimic care să se conformeze atât de bine la rațiune ca această tăgăduire a rațiunii.',
	'280. Cunoașterea lui Dumnezeu este foarte departe de iubirea pentru Dumnezeu.',

	'295. Al meu, al tău. "câinele ăsta e al meu", a spus copilul sărac, "acesta este locul meu sub soare". Iată începutul imaginii uzurpării pe tot pământul.',
	'300. Când un om puternic înarmat își păzește averea, averea lui e în pace',
	'305. Elvețienii sunt ofensați dacă li se spune gentilomi și se dovedesc a fi adevărații plebei pentru a fi considerați demni de o funcție înaltă.',
	'309. Justiția. Așa cum obiceiul determină ce este agreabil, la fel se întâmplă și cu justiția.',
	'312. Justiție înseamnă ceea ce este instaurat; și astfel toate legile noastre instaurate vor fi considerate obligatoriu ca fiind juste, fără a fi cercetate, de vreme ce sunt instaurate.',
	'321. Copii sunt uluiți când își văd tovarășii respectații.',
	'336. Motivele efectelor. Trebuie să ne păstrăm secretă gândirea și să judecăm totul cu ea, vorbind însă asemena oamenilor.',

	'344. Instinct și rațiune, mărcile a două naturi.',
	'345. Rațiunea ne poruncește mult mai imperios decât un stăpân; căci nesocotind-o pe prima suntem nenorociți și nesupunându-ne celui de-al doilea, suntem nebuni.',
]

function newQuote()
{
	var randomNumber = Math.floor(Math.random() * (quotes.length));
	document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];
}